name: file_picker_writable
description: |
  Flutter plugin to allow users to open files/documents which can be read, and written back at a
  later time as well as creating new files on external media.
version: 2.0.3
homepage: https://github.com/hpoul/file_picker_writable

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ">=1.0.0 <2.0.0"
  convert: ^3.0.0
  synchronized: ^3.0.0
  path_provider: ">=2.0.0 <3.0.0"
  path: ^1.8.0
  quiver: ">=3.0.0 <4.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1


flutter:
  plugin:
    platforms:
      android:
        package: codeux.design.filepicker.file_picker_writable
        pluginClass: FilePickerWritablePlugin
      ios:
        pluginClass: FilePickerWritablePlugin
      macos:
        pluginClass: FilePickerWritablePlugin

